// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa-XSHjhFozyFWVUATsJk1VFJnT1H42FA',
    appId: '1:326537564025:web:36617ddaedc7421daa29a8',
    messagingSenderId: '326537564025',
    projectId: 'lifelink-3122f',
    authDomain: 'lifelink-3122f.firebaseapp.com',
    storageBucket: 'lifelink-3122f.firebasestorage.app',
    measurementId: 'G-4S3YQBK2GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0mW-SLwndzEayNgJ_wLmyQtUqtuKfVo',
    appId: '1:326537564025:android:a088b5e682d385b7aa29a8',
    messagingSenderId: '326537564025',
    projectId: 'lifelink-3122f',
    storageBucket: 'lifelink-3122f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6TOTEehiwNTdGhzQAT0gHgYKJLJToM4Q',
    appId: '1:326537564025:ios:aea3720a6bb3dd5aaa29a8',
    messagingSenderId: '326537564025',
    projectId: 'lifelink-3122f',
    storageBucket: 'lifelink-3122f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6TOTEehiwNTdGhzQAT0gHgYKJLJToM4Q',
    appId: '1:326537564025:ios:aea3720a6bb3dd5aaa29a8',
    messagingSenderId: '326537564025',
    projectId: 'lifelink-3122f',
    storageBucket: 'lifelink-3122f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa-XSHjhFozyFWVUATsJk1VFJnT1H42FA',
    appId: '1:326537564025:web:0790a7c09fba38b9aa29a8',
    messagingSenderId: '326537564025',
    projectId: 'lifelink-3122f',
    authDomain: 'lifelink-3122f.firebaseapp.com',
    storageBucket: 'lifelink-3122f.firebasestorage.app',
    measurementId: 'G-V1YRHJQHV0',
  );
}
